#!/bin/bash

# Test commands for the new flat details flow

echo "🚀 TESTING NEW FLAT DETAILS FLOW"
echo "=================================="

echo ""
echo "1️⃣  STEP 1: Send OTP"
echo "curl -X POST 'http://localhost:8000/api/v1/signin' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"apt_id\": \"RAPKA\","
echo "    \"admin_email\": \"y.sandeepkumarreddy@gmail.com\""
echo "  }'"

echo ""
echo "2️⃣  STEP 2: Verify OTP (with NEW suggested_flat_details response)"
echo "curl -X POST 'http://localhost:8000/api/v1/verify-otp' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"apt_id\": \"RAPKA\","
echo "    \"admin_email\": \"y.sandeepkumarreddy@gmail.com\","
echo "    \"otp\": \"YOUR_OTP_HERE\""
echo "  }'"

echo ""
echo "Expected NEW response structure:"
echo "{"
echo "  \"status\": true,"
echo "  \"message\": \"OTP verified successfully\","
echo "  \"token\": {...},"
echo "  \"data\": {"
echo "    \"apt_id\": \"RAPKA\","
echo "    \"flat_id\": \"owner_RAPKA_405\","
echo "    \"user_id\": \"user_11\","
echo "    \"is_all_user_details_filled\": false,"
echo "    \"role\": \"owner\","
echo "    \"suggested_flat_details\": {           // 🆕 NEW!"
echo "      \"flat_number\": \"405\","
echo "      \"flat_floor\": \"4\""
echo "    }"
echo "  }"
echo "}"

echo ""
echo "3️⃣  STEP 3: Update flatmate details (with NEW flat fields)"
echo "curl -X PUT 'http://localhost:8000/api/v1/updateflatmatedetails' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -d '{"
echo "    \"user_name\": \"Sandeep Kumar\","
echo "    \"user_phone_number\": \"+91 9876543210\","
echo "    \"flat_number\": \"405\",                    // 🆕 NEW!"
echo "    \"flat_floor\": \"4\"                       // 🆕 NEW!"
echo "  }'"

echo ""
echo "Expected NEW response:"
echo "{"
echo "  \"message\": \"User details updated successfully\","
echo "  \"user_name\": \"Sandeep Kumar\","
echo "  \"user_phone_number\": \"+91 9876543210\","
echo "  \"flat_number\": \"405\",                      // 🆕 NEW!"
echo "  \"flat_floor\": \"4\",                         // 🆕 NEW!"
echo "  \"is_all_user_details_filled\": true          // ✅ NOW TRUE!"
echo "}"

echo ""
echo "4️⃣  STEP 4: Get flatmate details (to verify)"
echo "curl -X GET 'http://localhost:8000/api/v1/flatmatedetails' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN'"

echo ""
echo "=================================="
echo "✅ FEATURES IMPLEMENTED:"
echo "• OTP verification includes suggested flat details from invitations"
echo "• Update endpoint accepts flat_number and flat_floor"
echo "• Profile completion logic works correctly"
echo "• Elegant user experience with pre-filled suggestions"
echo "=================================="
